### ISSUE TITLE
cannot load apps ToonAppstore

### ISSUE THREAD

**Issue by Tobydeteckel** [ToonSoftwareCollective/toonstore_AppRepository#9]
Hi there,

Since yesterday i cant see  the apps in the store. all other network services works as normal,

firmware:5.33.9
tsc:2.1.4
Toon1

I found the issue after a TSC Update/PostNL App Update.

Toby,

**Comment by IgorYbema** [comment]
Thanks. We found an error in the xml file which contains all files.
Fixed
